create table Property  ( 
		 id int , 
		 mls_id int,
         title varchar(50),
         property_type int ,
         s_type int ,
         s_type_freq varchar(50),
         listing_branch smallint,
         name_number varchar(50),
         block_building varchar(50),
         street varchar(50),
         area varchar(50),
         district varchar(50),
         town_city varchar(50),
         province varchar(50),
         post_code varchar(50),
         country varchar(50),
         show_address smallint,
         locastate varchar(50),
         latitude varchar(50),
         longitude varchar(50),
         gbase_address varchar(50),
         concat_address varchar(50),
         short_description varchar(50),
         full_description varchar(50),
         sale_price decimal,
         rental_price decimal,
         rental_frequency varchar(50),
         call_for_price smallint,
         bedrooms int,
         bathrooms decimal,
         plot_sqft int,
         build_sqft int,
          year_built int,
         heating smallint,
         air_con smallint,
         garage decimal
		 )		 

